# Tree structure in Newick format, used in SmallPhylogeny
# example: "(ancestor:0(B.rapa:26,B.oleracea:28,B.nigra:70))"
tree_structure: "(e(o,f(c,d),g(a,b)))"

# Directory of the aligned genome data file
genome_file: "genomes_bad.txt"

# Genome reconstruction algorithm (not in use currently)
# algorithm: "GenomeAliquoting"
...
