# # # # # # # # # # # #
# - General options - #
# # # # # # # # # # # #

# Genome reconstruction algorithm to use
# [ SmallPhylogeny | DCJRearrangements | GenomeAliquoting | GenomeHalving ]
algorithm: [algorithm]

# Path to the aligned genome data file
# (Relative to pythgroups folder)
genome_file: [path]

# # # # # # # # # # # #
# - Small Phylogeny - #
# # # # # # # # # # # #

# Tree structure in Newick format,
# example: "(ancestor(B.rapa,B.oleracea,B.nigra))"
tree_structure: [tree]

# # # # # # # # # # # # # #
# - DCJ Rearrangements -  #
# # # # # # # # # # # # # #

# DCJ operations to perform.
# { inversion, translocation, fission, fusion }
operations:
  - inversion
  - translocation
  - fission
  - fusion

# The minimum number of chromosomes to maintain for fusion operations (>= 1)
minimum_chromosome: 1

# The maximum number of chromosomes for fission operations to produce (>= 2)
maximum_chromosome: 30

# Which chromosome to operate on (-1 for random, -2 for all of them)
which_chromosome: -2

# Maximum number of operations to perform (> 0)
number_of_operations: 10

# # # # # # # # # # # # # # #
# - Guided Genome Halving - #
# # # # # # # # # # # # # # #

# Which genome to replace (1 or 2 -- 0 for a random one)
genome_to_replace: 1
