# # # # # # # # # # # #
# - General options - #
# # # # # # # # # # # #

# Genome reconstruction algorithm to use
# [ SmallPhylogeny | DCJRearrangements | GenomeHalving ]
algorithm: SmallPhylogeny

# Path to the aligned genome data file (must be formatted for pathgroups as found in the TestData/InputData examples,
# unless use_gene_family_parser is enabled.
# (file Path is relative to the Pythgroups folder)
genome_file: TestData/InputData/SmallPhylogenyExample1.txt

# EXPERIMENTAL FEATURE: Hasn't been extensively tested. Doesn't work for the GenomeHalving algorithm
# Parse raw gene family data directly, rather than requiring the data to be formatted for pathgroups.
# Check out the config section of the manual for details on its formatting.
# [ True | False ]
use_gene_family_parser: False

# # # # # # # # # # # #
# - Small Phylogeny - #
# # # # # # # # # # # #

# Tree structure in Newick format
# Note that the non-median genome names must correspond to those found in the genome file
# while median genomes may be called anything (must have a name though)
tree_structure: (median1(genome1,median2(genome4,genome5),median3(genome2,genome3)))

# At the end, display the tree structure with calculated distances between nodes
# [ True | False ]
show_diagram: True

# Along with the calculated distances, calculate and show the number of each
# DCJ operation performed between each median and their neighbors.
# Notes: Be sure to configure DCJ Rearrangements below. May take longer to compute!
# [ True | False ]
show_DCJR: True

# The number of optimization rounds to perform.
# A lower number will take less time but may affect accuracy, while anything greater than 50 has minimal effect.
# Must be at least 0 (skips optimization step if 0). Default: 50
optimization_rounds: 50

# # # # # # # # # # # # # #
# - DCJ Rearrangements -  #
# # # # # # # # # # # # # #

# DCJ operations to perform
# Disable operations by commenting them out with a '#'
# Note: the fission and fusion operations sometimes cause errors, if so then one or both of them should be disabled.
# { inversion, translocation, fission, fusion }
operations:
  - inversion
  - translocation
#  - fission
#  - fusion

# True: Print the chromosomes at each rearrangement step along with the operation counts.
# False: Print just the final operation counts
# [ True | False ]
verbose_output: False

# The minimum number of chromosomes to maintain for fusion operations (>= 1) Default: 1
minimum_chromosome: 1

# The maximum number of chromosomes for fission operations to produce (>= 2) Default: 30
maximum_chromosome: 30

# Which chromosome to operate on (-1 for random, -2 for all of them) Default: -2
# [ -1 | -2 ]
which_chromosome: -2

# Maximum number of operations to perform per cycle (> 0) Default: 10
number_of_operations: 10

# # # # # # # # # # # # # # #
# - Guided Genome Halving - #
# # # # # # # # # # # # # # #

# Which genome to replace (1 or 2 -- 0 for a random one) Default: 1
# [ 0 | 1 | 2 ]
genome_to_replace: 1
